

Vagrant.configure("2") do |config|
  config.vm.define "serviceObjectData" do |serviceObject|
    serviceObject.vm.box = 'azure'

    # use local ssh key to connect to remote vagrant box
    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end

    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "provision.yml"
    end

  end

  config.vm.define "serviceImageData" do |serviceImage|
    serviceImage.vm.box = 'azure'

    # use local ssh key to connect to remote vagrant box
    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|


      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end

    config.vm.network "forwarded_port", guest: 80, host: 8080

    serviceImage.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end
  end

end