version: '3'
services:
  api:
    build: ./
    depends_on:
      - mongo
    ports:
      - "80:8080"
  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo: null